name: Global Environment Variable

on:
    push:
        branches:
            - main

env:
    COURSE: GitHub Actions

jobs: 
    demo:
        runs-on: ubuntu-latest

        steps:
            - name: Print Course
              run: echo "Learning $COURSE"